name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '**/*.yml'
      - '*.code-workspace'
      - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '**/*.yml'
      - '*.code-workspace'
      - '.gitignore'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    uses: ./.github/workflows/package.yml

  openapi:
    uses: ./.github/workflows/openapi.yml

  release:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/release.yml
    needs: [build, package, openapi]
    secrets: inherit
